### ISSUE TITLE
Cannot build project, tslib missing

### ISSUE THREAD

**Issue by mputnieks** [WrathChaos/react-native-text-input-interactive#1]
Dear developers, thank you for releasing this, I tried incorporating it in my project, yet got the following error.
My cmd log: 

Failed building JavaScript bundle.
Unable to resolve module tslib from C:\Users\mikel\AwesomeProject\node_modules\react-native-text-input-interactive\build\dist\InteractiveTextInput.js: tslib could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  1 | "use strict";
  2 | Object.defineProperty(exports, "__esModule", { value: true });
 >3 | const tslib_1 = require("tslib");
    |                          ^
  4 | const React = tslib_1.__importStar(require("react"));
  5 | const react_native_1 = require("react-native");
  6 | /**

**Comment by kuraydev** [comment]
Hello @mputnieks 
Thank you for this report. Typescript libraries requires `tslib` as a dev dependency or global dependency. Simply run this command: 
```
npm i -D tslib
OR
npm i -g tslib
```

Then everything should work as expected.

**Comment by mputnieks** [comment]
Thank you! Ran the global one first - did not fix anything, then I tried the dev dependency and everything works now.

**Comment by kuraydev** [comment]
@mputnieks If you have any question, feel free to ask please :)
