### ISSUE TITLE
change background color and the font for the text 

### ISSUE THREAD

**Issue by moumnimohamed** [WrathChaos/react-native-text-input-interactive#3]
please how can I change the background color and fontFamily for the text

<img width="265" alt="image" src="https://user-images.githubusercontent.com/21304554/195953353-6829f8d3-046b-4201-96eb-89a3f6cf9756.png">

**Comment by kuraydev** [comment]
Hello @moumnimohamed 

You can customize it like this: 

```
textInputStyle={{
   backgroundColor: 'pink',
   fontFamily: 'Staatliches-Regular',
}}
```

You can also checkout the updated `example` project :)
